const levels = [
    {
        id: 1,
        grid: [
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'Start', 'empty'],
            ['path', 'path', 'path', 'path', 'path', 'path', 'path', 'path', 'path', 'empty'],
            ['path', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty'],
            ['path', 'empty', 'path', 'path', 'path', 'path', 'path', 'path', 'path', 'empty'],
            ['path', 'empty', 'path', 'empty', 'empty', 'empty', 'empty', 'empty', 'path', 'empty'],
            ['path', 'empty', 'path', 'empty', 'path', 'path', 'path', 'empty', 'path', 'empty'],
            ['path', 'empty', 'path', 'empty', 'End', 'empty', 'path', 'empty', 'path', 'empty'],
            ['path', 'empty', 'path', 'empty', 'empty', 'empty', 'path', 'empty', 'path', 'empty'],
            ['path', 'empty', 'path', 'path', 'path', 'path', 'path', 'empty', 'path', 'empty'],
            ['path', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path', 'empty'],
            ['path', 'path', 'path', 'path', 'path', 'path', 'path', 'path', 'path', 'empty'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty'],
        ],
    },
    {
        id: 2,
        grid: [
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'End', 'empty'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path', 'path', 'path', 'empty'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path', 'empty', 'empty', 'empty'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path', 'path', 'path', 'empty'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path', 'empty'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path', 'path', 'path', 'empty'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path', 'empty', 'empty', 'empty'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path', 'empty', 'empty', 'empty'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path', 'path', 'path', 'empty'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path', 'empty'],
            ['empty', 'path', 'path', 'path', 'path', 'path', 'path', 'path', 'path', 'empty'],
            ['empty', 'Start', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty'],
        ],
    },
    {
        id: 3,
        grid: [
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'End'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'path'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'path', 'path', 'path', 'empty', 'path'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'path', 'empty', 'path', 'empty', 'path'],
            ['empty', 'empty', 'empty', 'empty', 'empty', 'path', 'empty', 'path', 'empty', 'path'],
            ['empty', 'empty', 'path', 'path', 'path', 'path', 'empty', 'path', 'empty', 'path'],
            ['empty', 'path', 'path', 'empty', 'empty', 'empty', 'empty', 'path', 'path', 'path'],
            ['empty', 'path', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty'],
            ['empty', 'path', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty'],
            ['empty', 'Start', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty'],
        ],
    },
];

export default levels;